### ISSUE TITLE
error page Generating new download key

### ISSUE THREAD

**Issue by thekksed** [hklcf/MediaFire-Stream-API#9]
I think the file access is restricted by IP. Once a file gets accessed too many times from a single IP, it will show a page to Generating new download key with 5 seconds countdown. 

Is there a way to solve this?

**Comment by hklcf** [comment]
other file have this repair page at the same time?

**Comment by thekksed** [comment]
No, I have noticed that files downloaded over 1000 times will have this repair page.

**Comment by hklcf** [comment]
over 1000 times with-in 24 hours?

**Comment by thekksed** [comment]
That I don't know, could be. But files that are days old still have the repair page, so there doesn't seems to be a reset timer.

**Comment by hklcf** [comment]
I'll do some test on this

**Comment by hklcf** [comment]
After some test on this, I found that mediafire will add a repair download page to the "download link" (file id), that means anyone who use the same download link to generate direct link also will redirect to the repair page.

The only way to fix is re-upload the file to generate a new "download link" (file id) and get direct link using the new download link. :cry:
